# CBB API Configuration
# This is the base URL for the external College Basketball Data API.
cbb.api.base-url=https://api.collegebasketballdata.com/

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
